---
- hosts: localhost
  tasks:
  - name: Create task definition
    ecs_taskdefinition:
      aws_access_key: AKIAJLVQWZMK4ZVNSNLQ
      aws_secret_key: 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
      region: us-east-1
      family: mytestauto
      revision: REVISION_NO
      containers:
      - name: web
        memory: 300
        essential: true
        image: "mohanraz/myapachewells"
        mountPoints:
          - containerPath: /var/www/html
            sourceVolume: web_var_www_html
        portMappings:
          - containerPort: 80
            hostPort: 80
      - name: javabackend
        memory: 300
        essential: true
        image: "mohanraz/myjavawells"
      volumes:
      - name: web_var_www_html
      state: present
    register: task_output
  - name: Create ECS Service
    ecs_service:
        aws_access_key: AKIAJLVQWZMK4ZVNSNLQ
        aws_secret_key: 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
        region: us-east-1
        state: present
        name: test-service
        cluster: weclusters
        task_definition: mytestauto:REVISION_NO
        desired_count: 3
        load_balancers: wordpress
        deployment_configuration:
          minimum_healthy_percent: 50
          maximum_percent: 200
